#!/bin/bash
echo "part 1"
grep "blockID=\"g[[:digit:]]\+\"\|blockID=\"i[[:digit:]]\+\"" blocklist.xml
echo "part 2"
grep "id=" blocklist.xml | grep "@.*\." | grep -v 'id.*\\' | grep -v 'id.*\/' | grep -v 'id.*\^'
